### ISSUE TITLE
Sony - Playstation - Issues noticed with incorrect/missing clones, renames, etc.

### ISSUE THREAD

**Issue by retroNUC** [unexpectedpanda/retool#127]
Reporting any issues I noticed as go through my PSX collection with latest redump dat:
## Dat
Sony - PlayStation (2021-09-29 02-04-02)

### New Clones
- [x] `Beat Mania 3rd Mix Mini (Japan)` is a clone of `Beat Mania Append 3rdMix (Japan)` _(preview release with limited selection of songs - https://remywiki.com/CS_bm_3rd)_
- [x] `Blaster Master (Japan)` is a clone of `Blaster Master - Blasting Again (USA)` _(same game - https://en.wikipedia.org/wiki/Blaster_Master:_Blasting_Again)_
- [x] `Block Kuzushi - Kowashite Help! (Japan)` is a clone of `Block Kuzushi (Japan)` _(Major Wave release takes priority - http://redump.org/disc/33940/)_
- [x] `Bottom of the 9th - Major League Heroes (Japan)` is a clone of `Bottom of the 9th (USA)` _(same game)_
- [x] `Bugi (Japan)` is a clone of `Kensei - Sacred Fist (USA)` _(same game - https://en.wikipedia.org/wiki/Kensei:_Sacred_Fist)_
- [x] `Bust A Move (Japan) (Disc 1) (Genteiban)` is a clone of `Bust A Move (Japan)` _(special edition)_
- [x] `Chou Kousoku Gran Doll (Japan)` is a clone of `Chou Kousoku Gran Doll (Japan) (Disc 1) (Premium Edition)` _(old redump names)_
- [x] `Chou-Kousoku Gran Doll (Japan)` is a clone of of `Chou-Kousoku Gran Doll (Japan) (Disc 1) (Premium Edition)` _(new redump names)_
- [x] `Criticom - The Critical Combat (Japan)` is a clone of `Criticom (USA)`
- [x] `DigimonWorld - Digital Card Arena (Japan)` is a clone of `Digimon - Digital Card Battle (USA)` _(potential recent redump rename)_
- [x] `Disney's Mulan - Story Studio (Europe)` is a clone of `Disney's Story Studio - Mulan (USA)` _(potential recent redump rename)_
- [x] `DonPachi (Japan)` is a clone of `DonPachi (Japan) (Cyclone's Best)` _("reprint" should take priority?)_
- [x] `Doukyuusei 2 (Japan)` is a clone of `Doukyuusei 2 (Japan) (Extra Box)` _(special edition, but same content)_
- [x] `Dungeon Creator (Japan)` is a clone of `Dungeon Creator (Japan) (Disc 1)` _(from 2-disc limited edition)_
- [x] `Exciting Bass (Japan)` is a clone of `Fisherman's Bait - A Bass Challenge (USA)`
- [x] `Exciting Bass 2 (Japan)` is a clone of `Fisherman's Bait 2 - Big Ol' Bass (USA)`
- [x] `Exciting Bass 3 (Japan)` is a clone of `Big Ol' Bass 2 (USA)`
- [x] `Formation Soccer '98 - Ganbare Nippon in France (Japan)` is a clone of `Formation Soccer '98 (Japan)` _(latter is a Major Wave reprint, takes priority)_
- [x] `Gundam the Battle Master 2 (Japan)` is a clone of `Gundam Battle Assault (USA)`
- [x] `Hana to Ryuu (Japan)` is a clone of `Hana to Ryuu - Hanafuda, Mahjong (Japan) (Major Wave)` _(Major Wave release takes priority)_
- [x] `International Moto-X (Japan)` is a clone of `International Moto X (Europe) (En,Fr,De,Es,It,Nl)` _(same game)_
- [x] `Jackie Chan Stuntmaster (Europe) (Recalled)` is a clone of `Jackie Chan Stuntmaster (USA)` _(or potentially excluded altogether, as it's a non-working retail release that was reissued by Sony - https://www.reddit.com/r/psx/comments/cya404/redump_standing_at_the_edge_of_the_end_in_sony/)_
- [x] `Kileak, The Blood 2 - Reason in Madness (Japan)` is a clone of `Epidemic (USA)` _(same game)_
- [x] `Kiwame Daidougi - Tsumuya Tsumazaruya (Japan)` is a clone of `Kiwame Daidougi (Japan) (Major Wave)` _(reprint takes priority)_
- [x] `Lagnacure (Japan, Asia)` is a clone of `Lagnacure (Japan) (Artdink Best Choice)` _(reprint takes priority)_
- [x] `Little Princess - Marl Oukoku no Ningyou-hime 2 (Japan)` is a clone of `Little Princess - Marl Oukoku no Ningyou-hime 2 (Japan) (Disc 1) (+1 Tasu Ichi)` _(same content, 2-disc special edition takes priority)_
- [x] `Lode Runner - The Legend Returns (Japan)` and `Lode Runner Extra (Japan)` are both clones of `Lode Runner (USA)` _(US release is a 2-in-1 compilation - https://www.mobygames.com/game/playstation/lode-runner___/cover-art/gameCoverId,103205/)_

### New Clones (Simple 1500 Series)
- [x] `Simple 1500 Series Vol. 67 - The Soccer - Dynamite Soccer 1500 (Japan)` is a clone of `Dynamite Soccer 98 (Japan)`

### New Clones (SuperLite 1500 Series)
- [x] `SuperLite 1500 Series - A Ressha de Ikou Z - Mezase! Tairiku Oudan (Japan)` is a clone of `A Ressha de Ikou Z - Mezase! Tairiku Oudan (Japan)`
- [x] `SuperLite 1500 Series - A5 - A Ressha de Ikou 5 (Japan)` is a clone of `A5 - A Ressha de Ikou 5 (Japan)`
- [x] `SuperLite 1500 Series - Asuka 120% Final - Burning Fest. Final (Japan)` is a clone of `Asuka 120% Final - Burning Fest. Final (Japan)`
- [x] `SuperLite 1500 Series - Fantastic Night Dreams - Cotton Original (Japan) ` is a clone of `Fantastic Night Dreams - Cotton Original (Japan)`
- [x] `SuperLite 1500 Series - Lode Runner - The Legend Returns (Japan)` is a clone of `Lode Runner - The Legend Returns (Japan)`
- [x] `SuperLite 1500 Series - Pao Leeming Kanshuu - Fuusui Nyuumon (Japan)` is a clone of `Pao Leeming Kanshuu - Fuusui Nyuumon (Japan)`
- [x] `SuperLite 3in1 Series - Crossword-shuu (Japan)` is a clone/compilation of following titles:
- `SuperLite 1500 Series - Crossword (Japan)`
- `SuperLite 1500 Series - Crossword 2 (Japan)`
- `SuperLite 1500 Series - Crossword 3 (Japan)`

### Incorrect Clones
- [x] `America Oudan Ultra Quiz (Japan) (Fukkokuban)` should be clone of `America Oudan Ultra Quiz (Japan)`  _("reprint" should take priority?)_
- [x] `Armored Core (USA)` should be clone of `Armored Core (USA) (Reprint)` _("reprint" should take priority?)_
- [x] `Ayrton Senna Kart Duel Special (Japan)` should **not** be a clone of `Ayrton Senna Kart Duel (Europe)` _(unique game, released in 1999 after Kart Duel 1 & 2 - https://www.youtube.com/watch?v=YsoHM220E4E / https://www.youtube.com/watch?v=woKIW-025kU / https://www.youtube.com/watch?v=nD_WfqjuSuM)_
- [x] `Victory Boxing Contender (Europe)` should be a clone of `Contender 2 (USA)` _(judging by player select / gameplay - https://www.youtube.com/watch?v=gLZQiqq68C0 / https://www.youtube.com/watch?v=v49gjN1dgsA)_
- [x] `Victory Boxing Challenger (Europe) (En,Fr,De,Es)` should be a clone of `Victory Boxing (Japan)`
- [x] `Dance Dance Revolution (Japan)` should **not** be a clone of `Dance Dance Revolution (USA)` _(two different games, released years apart - https://remywiki.com/CS_DDR_1st_JP / https://remywiki.com/CS_DDR_NA)_
- [x] `Hot Shot (Europe)` should **not** be a clone of `Wanted (Europe)` _(complete reskin, but some gameplay differences i.e. tank enemies - https://www.youtube.com/watch?v=jH_smNDGZRM / https://www.youtube.com/watch?v=7ogcQ2vEcYk)_
- [x] `Space Invaders (Japan)` should **not** be a clone of `Space Invaders (USA)` _(different game, Japanese version of US title is 'Space Invaders X')_
- [x] `SuperLite 1500 Series - Strikers 1945 II (Japan)` should be a clone of `Strikers 1945 (USA)` _(second game in the series)_

Victory Boxing entries above are confusing and lots of sources seem to be wrong, so here's my own investigation of pairings:
```
- Contender (USA) / Dynamite Boxing (Japan) / Victory Boxing 2 (Europe)
- Contender 2 (USA) / Victory Boxing Contender (Europe) / NO NTSC-J RELEASE(?)
- NO NTSC-U RELEASE / Victory Boxing Challenger (Europe) (En,Fr,De,Es) / Victory Boxing (Japan)
- NO NTSC-U RELEASE / Victory Boxing Champion Edition (Europe) / Kensei - The King of Boxing (Japan)
```

### Renames
- [x] Parent game of P/C rule `Board Game - Top Shop (USA)` has been renamed to `Top Shop (USA)` in latest redump dat

### Misclassification
- [x] `Fushigi na Data Disc (Japan, Asia) (Disc 2)` and `Fushigi na Data Disc 2 (Japan, Asia)` should be classed as Demo, not Bonus Disc _(old/new redump names)_
- [x] `Kowloon's Gate (Japan) (Special Disc)` should be classed as Demo, not Special Disc _(appears to be part of the game's first disc - https://muuseo.com/veru/items/407)_

**Comment by unexpectedpanda** [comment]
Thanks for the hard work here -- I'll work through these for the next release.

**Comment by retroNUC** [comment]
Cheers. I'll keep adding new points to the original post as I find them.

**Comment by unexpectedpanda** [comment]
It turns out `DonPachi (Japan) (Cyclone's Best)` isn't selected because Redump lists Japanese as its language, whereas the original lists English. So this is Retool operating as intended when an English speaking region is high priority -- if there's an error here, it needs to be fixed on the Redump side.
