### ISSUE TITLE
Sony PlayStation - Clone Cleanup

### ISSUE THREAD

**Issue by retroNUC** [unexpectedpanda/retool#204]
Findings based on Sony - PlayStation (2022-04-30 01-34-37), I'll be back with more at some point...

## Missing Clones
- [x] `Baby Universe (Europe)` and `3D-Kaleidoscope - Baby Universe (Japan)`
- [x] `Skydiving Extreme (USA)` and `Aerodive (Japan)`
- [x] `Backstreet Billiards (USA)` and `Carom Shot 2 (Japan)`
- [x] `Gekioh - Shooting King (USA)` and `Arcade Hits - Shienryuu (Japan)`
- [x] `Rascal (USA)` and `Bubblegun Kid (Japan)`
- [x] `TNN Motor Sports HardCore 4X4 (USA)` and `Deka Yonku - Tough the Truck (Japan)`
- [x] `City of Lost Children, The (USA) (En,Es,It)` and `Lost Children - The City of Lost Children (Japan)`
- [x] `Rush Hour (USA)` and `BattleRound USA (Japan)`
- [x] `Digimon - Digital Card Battle (USA)` and `DigimonWorld - Digital Card Battle (Japan)`
- [x] `Pool Academy (Europe) (En,Fr,De)` and `Doukyuu re-mix - Billiards Multiple (Japan)`
- [x] `Arcade Hits - Wolf Fang - Kuuga 2001 (Japan)` and `Wolf Fang - Kuuga 2001 (Japan)`
- [x] `WWF SmackDown! (USA)` and `Exciting Pro Wres (Japan)`
- [x] `World Cup Golf - Professional Edition (USA)` and `World Cup Golf - In Hyatt Dorado Beach (Japan) `
- [x] `Pro Evolution Soccer 2 (Europe) (En,Fr,De)` and `World Soccer Winning Eleven 2002 (Japan)`
- [x] `Magical Drop (Japan)` and `Arcade Hits - Magical Drop (Japan)`
- [x] `Family Games Compendium (Europe) (Disc 1)` and `Vegas Casino (Europe)`
- [x] `Family Games Compendium (Europe) (Disc 2)` and `Family Card Games Fun Pack (USA)`
- [x] `Explosive Racing (Europe)` and `X.Racing (Japan)`
- [x] `Yu-Gi-Oh! Forbidden Memories (USA)` and `Yu-Gi-Oh! Shin Duel Monsters - Fuuin Sareshi Kioku (Japan)`

## Missing Clones (With Additional Notes)
- [x] `Cocktail Harmony (Japan)` and `Simple 1500 Jitsuyou Series Vol. 06 - Cocktail no Recipe (Japan)`
	- Simple 1500 release is a cut-down version with no Story Mode, original should take preference
- [ ] `Community Pom - Omoide o Dakishimete (Japan)` and `Community Pom (Japan)`
	- Without subtitle is original 1997 release, with subtitle is later 1999 re-release
	- Source - https://www.romhacking.net/translations/6301/
- [ ] `Tales of Fandom Vol. 1 - Cless Version (Japan)` and `Tales of Fandom Vol. 1 - Mint Version (Japan)`
	- Exactly the same disc contents, just a different cover
- [ ] `Wai Wai Bowling (Japan)` and `Family Bowling (Japan)`
	- Wai Wai Bowling is newer name used for 2003 Major Wave re-release
- [ ] `Zap! Snowboarding Trix '98 (Japan)` and `Zap! Snowboarding Trix (Japan) (Fukyuuban 1500)`
	- Same game, just dropped '98 in title for later budget re-release
- [ ] `Yamasa Digi Selection (Japan)` and `Yamasa Digi Selection (Japan) (DX)`
	- DX version had physical collectibles in pack, discs are the same
- [ ] `Family Games Compendium (Europe) (En,Fr,De,It) (Disc 3)` is compilation of these three games:
	- [ ] `Kart Challenge (Europe) (En,Fr,De,It)`
	- [ ] `Sports Superbike (Europe) (En,Fr,De,It)`
	- [ ] `GP Challenge (Europe) (En,Fr,De,It)`

## Incorrect Clones
- [ ] `Chou Sentou Kyuugi Vanborg (Japan)` and `V-Ball - Beach Volley Heroes (Europe)`
	- Different enough that I wouldn't consider these the same game
- [ ] `Culdcept - Expansion (Japan)` and `Culdcept - Expansion Plus (Japan)`
	- Different content, released at a different time 
- [ ] `Dave Mirra Freestyle BMX (USA) (Rev 1)` and `Dave Mirra Freestyle BMX - Maximum Remix (USA)`
- [x] `Virus - It Is Aware (Europe) (En,Fr,De,Es,It)` and `Virus - The Battle Field (Japan)`
	- Two completely different games, the latter being a Japanese-only card based RPG
- [ ] `Marie no Atelier Plus - Salburg no Renkinjutsushi (Japan)` and `Marie no Atelier - Salburg no Renkinjutsushi (Japan)`
- [x] `K-1 Grand Prix (USA)` and `Fighting Illusion V - K-1 Grand Prix '99 (Japan)`
	- Correct clone of USA is actually `Fighting Illusion - K-1 Grand Prix '98 (Japan)`

**Comment by retroNUC** [comment]
Ticked off the simpler ones currently fixed in that pull request, might need someone else's judgement on the rest.

**Comment by unexpectedpanda** [comment]
Thanks! I'll take a look next time I'm updating the clone lists.

**Comment by unexpectedpanda** [comment]
I'm still working through the list, but I figured because I've spent too much time researching these titles, I should document it now so people don't have to do the work again... 😅

Basically, _Chou Sentou Kyuugi Vanborg_ looks a lot like a reskin of _V-Ball - Beach Volley Heroes_, with an extra intro video. It's not so much, say, _Heretic_ compared to _Doom_, but more like cosmetic tweaks the development team thought would go down well in a different market. Maybe a localized v1.1 versus a v1.0?

Usually, I consider reskins to be clones, especially if the experience is materially the same. That threshold is going to be different for different people -- but I have to draw the line somewhere.

I should point out I might have missed something important when comparing the titles. I found out quickly I wasn't very good at the game, so needed to cross reference on YouTube to get extra information. My Japanese is also minimal, so it's not so easy to pick out all the differences. If you know of extra differences that might sway me to unlink them (for example, the opponents not being just reskins), definitely let me know!

## V-Ball - Beach Volley Heroes vs Chou Sentou Kyuugi Vanborg (Japan)

* _V-Ball_ was released in Europe in 1998. _Chou_ is a modified version of the game released in Japan months later in 1999.
* The gameplay seems to be identical.
* _Chou_ has a video at the beginning that isn't in _V-Ball_. I've seen this described somewhere as a "story" that's been added, but it doesn't look like any other story elements enter into the game itself. The ending for both games is similar: the characters you chose have a conversation, then the credits roll.
* The interface is different between the games, but seems to convey the same information.
* The title screen, end credits background, and loading graphics are different.
* There is different music in each game.
* There are some shared courts to play on, but so far it looks like there are also unique courts in each game. This does not affect gameplay in any way, as they're more akin to fighting stages than levels.
* I am unable to tell if the players are just reskins, or if they have unique animations. This is because I have no idea how to execute the special moves, and I can't seem to win a game either -- oh for a manual! I'm also not sure if stats are different between the characters in each version, and if that changes how challenging they are.
* You can buy things between matches in both versions of the game. I'm not sure if the items are the same or not.
* The default control schemes in each game are different, but this can be easily changed.
* This might be a common thing in Japanese PlayStation games, but I don't know for sure as I generally don't play them! In menus in _Chou_, the functions for circle and X are reversed compared to _V-Ball_. In _Chou_, to accept in a menu, you press circle. To cancel/go back, you press X. This makes sense as when marking something in Japan, ◯ means correct (instead of a tick), ✕ means incorrect.

### Courts in both games
* Chinese garden
* Hotel (?). Greek columns next to the court, pool in the background.
* Park.
* Tropical beach, with a catamaran and surfboards.

### Unique courts in _V-Ball_
* Air carrier.
* Casino.
* Soccer field.
* Beach 2, with two large stands with people in them, and crowd at court level. Crowd has yellow shirts.
* Beach 3, with wooden panelling separating the court from the crowd. This barrier has two kanji on it.

### Unique courts in _Chou_
* Bridge (?) in a non-distinct Asian location. Wooden arches on three sides. Rocks in the mist in the background.
* Factory.
* Forest (?). Crowd wears tribal masks.
* Medieval (?). Towers in the background and a cobblestone court.
* Spaceship. Another spaceship, earth, and space in the background.

**Comment by unexpectedpanda** [comment]
This is the info I have on _Culdcept - Expansion_ vs _Culdcept - Expansion Plus_. While I haven't played them, _Plus_ just looks like an updated version from the outside.

> Culdcept Expansion is an original fantasy board game for the Japanese Playstation that was released in Japan on May 1, 1999 for 5800 yen... It was followed by Culdcept Expansion Plus, a slightly newer version with a map editor that was sold for 2800 yen.
>
> https://psxdatacenter.com/games/J/C/SLPM-86658.html

> Culdcept's initial release was Japan-only on the Sega Saturn in 1997, and later, an upgraded port, Culdcept Expansion, was released on the [PlayStation](https://en.wikipedia.org/wiki/PlayStation) in 1999.[<sup>1</sup>](https://en.wikipedia.org/wiki/Culdcept#cite_note-:0-1) This saw a re-release as Culdcept Expansion Plus in 2000.
>
> https://en.wikipedia.org/wiki/Culdcept

> ...then finally Plus came out the year after that, which is identical to Expansion bar the ability to use twenty maps that appear to have previously been for promotional use (there’s a Famitsu map and some tournament maps in there).
>
> http://kimimisblog.blogspot.com/2014/02/culdcept-expansion-plus.html

Looks like the [cards are shared between the games too](https://culdceptcentral.com/culdcept-satps1/culdcept-satps1-card-lists).

**Comment by retroNUC** [comment]
Yeah, I suppose there's subjective flexibility when it comes to clones, but final call is always up to you - It's your database, after all! 🙂

For my own personal rule preferences:
- I consider Clones as games with the same features/content, or implemented revisions or localizations
- If a game is marketed as a separate release with new features, expanded content, or released under a new name, I personally would not consider it a Clone and I'd rather it be a separate entry in my collection (but I can see how others would consider it a Clone in the traditional MAME sense of the word)

Also, if you're documenting regional differences, I'd suggest submitting those to TCRF for greater visibility to the community.

**Comment by retroNUC** [comment]
Also, the comment on Atelier Marie - That quote compares the second PS1 release of the game ('Plus') against the sole Saturn release ('v1.3').

'Plus' compared with the original PS1 release (no title suffix) have more differences than just DualShock support, as it includes all the changes that were in the Saturn port, such as new endings, tweaks, etc.

**Comment by unexpectedpanda** [comment]
There's already functionality in Retool v2 (the ever ongoing background project) to point to different clone lists on the hard drive, and to download them from different locations. So it's entirely possible people can maintain different standards going forward if they wish. Whether people can be bothered doing that is another thing altogether :)

> Also, if you're documenting regional differences, I'd suggest submitting those to TCRF for greater visibility to the community.

Region comparisons are definitely not something I'll be doing regularly, only when people have questions about choices I've made along the way. To do a proper job for TCRF, I'd need to spend a lot of time with each version of the game, and potentially have fluency in another language.

> 'Plus' compared with the original PS1 release (no title suffix) have more differences than just DualShock support, as it includes all the changes that were in the Saturn port, such as new endings, tweaks, etc. But I think by your definition, it's still a Clone.

Thanks for the extra detail! You're right about it still being a clone by my definition, but it helps to have accurate information all the same.

**Comment by unexpectedpanda** [comment]
Merged your PR in -- I'll need to update the `hash.json` then it should be available to everyone.
