### ISSUE TITLE
Sony PlayStation 2

### ISSUE THREAD

**Issue by Florin9doi** [unexpectedpanda/retool#206]
## Dat
Sony PlayStation 2

## Missing Clones

- [ ] ATV Offroad Fury 4 (Europe) (En,Fr,De,Es,It,Pt,Pl,Ru,El)
ATV Offroad Fury 4 (USA) (Layer 0) (Beta)
ATV Offroad Fury 4 (USA) (Layer 1) (Beta)
- [ ] ~~Buzz! Brain of the World
Buzz! Norgesmester (Europe) (En,No,Da)~~
- [ ] Zone of the Enders - The 2nd Runner (USA)
Zone of the Enders - The 2nd Runner (Europe) (En,Fr,De,Es,It) (Special Edition)
- [ ] Roland Garros French Open 2002 (Europe) (En,Fr,De,Es,It,Pt)
US Open 2002 - A USTA Event (Japan)
- [ ] Ghost Master - The Gravenville Chronicles (Europe) (En,Fr,De,Es,It)
Gravenville - Ghost Master Chronicles (USA) (Beta)
- [ ] PS2 Linux Beta Release 1 (Japan) (En,Ja)
Linux (for PlayStation 2) Release 1.0 (Europe) (Disc 1) (Runtime Environment)
- [ ] Lethal Skies II (Europe)
Sidewinder V (Japan) (En,Ja) (Flight Box)
- [ ] Sidewinder Max
Iron Eagle Max
- [ ] Metal Gear Solid 3 - Subsistence (Europe) (En,Fr) (Disc 1) (Subsistence)
Metal Gear Solid 3 - Subsistence (Europe) (En,Fr) (Beta)
- [ ] WRC - Rally Evolved (Europe) (En,Fr,De,Es,It,Pt,No,Fi) (v2.00)
WRC 5 WT (Europe) (Beta)
- [ ] Psyvariar: Complete Edition
  - Compilation of :
     - SuperLite 2000 Vol. 10 - Psyvariar - Revision (Japan)
     - SuperLite 2000 Vol. 8 - Psyvariar - Medium Unit (Japan)

**Comment by unexpectedpanda** [comment]
Thanks for this. I'll take a look when I next update the clone lists.
